import React, { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { Alert, Form, Button } from "react-bootstrap";
import got from "got";

export default function Home({ randomJoke, categories }) {
  const [selectedCategory, setSelectedCategory] = useState(categories[""]);
  const [currentJoke, setCurrentJoke] = useState(randomJoke.value);

  // useEffect(() => {
  //   const res = async () => {
  //     return await got(`https://api.chucknorris.io/jokes/random?category=${category}`).json();
  //   }
  // });

  // const getJoke = () => {
  //   setCurrentJoke("Test");
  // };

  const getJoke = async () => {
    const joke = await got(
      `https://api.chucknorris.io/jokes/random?category=${selectedCategory}`
    ).json();
    return setCurrentJoke(joke.value);
  };
  const handleClick = (event) => {
    event.preventDefault();
    getJoke();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Chuck Norris React App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          alt="Chuck Norris"
          src="/chucknorris_logo_coloured_small.png"
          width="360px"
          height="219px"
        />
        <h3 className={styles.title}>Welcome to Chuck Norris Jokes</h3>

        {/* <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p> */}

        <div className={styles.grid}>
          <Alert variant="success">{currentJoke}</Alert>
        </div>
        <p>Select category</p>
        <div className={styles.grid}>
          <Form.Select
            value={selectedCategory}
            aria-label="Default select example"
            onChange={(e) => setSelectedCategory(e.target.value)}
          >
            <option>Random</option>
            {categories.map((category, index) => (
              <option key={index} value={category}>
                {category}
              </option>
            ))}
          </Form.Select>
          <Button variant="primary" onClick={handleClick}>
            Get joke
          </Button>
        </div>
      </main>

      <footer className={styles.footer}>Petro Franko</footer>
    </div>
  );
}
export async function getServerSideProps() {
  const randomJoke = await got(
    "https://api.chucknorris.io/jokes/random"
  ).json();
  const categories = await got(
    "https://api.chucknorris.io/jokes/categories"
  ).json();
  // const jokeByCategory = await got(
  //   `https://api.chucknorris.io/jokes/random?category=${params.category}`
  // ).json();

  return {
    props: {
      randomJoke,
      categories,
    },
  };
}
